/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package libraray;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lelo
 */
public class Librarybookmgmt extends javax.swing.JFrame {
PreparedStatement pst=null;
PreparedStatement pst1=null;
    Connection con=null;
     ResultSet rst=null;
    public Librarybookmgmt() throws ClassNotFoundException, SQLException {
        initComponents();
        Class.forName("com.mysql.jdbc.Driver");
         con = DriverManager.getConnection("jdbc:mysql://localhost:3306/librar", "root", "root");
        update_table();
        CurrentDate();
    Fillcombo();
    }
    
    public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
     private void update_table() {
        try{
            String mysql = "select * from TblBooks";
            pst = con.prepareStatement(mysql);
            rst = pst.executeQuery();
           TblBook.setModel(DbUtils.resultSetToTableModel(rst));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
      public void CurrentDate(){


Thread clock = new Thread(){

public void run(){
  for(;;){
      try {
          Calendar cal = new GregorianCalendar();
int month = cal.get(Calendar.MONTH);
int year = cal.get(Calendar.YEAR);
int day = cal.get(Calendar.DAY_OF_MONTH);
date_text.setText("Date  "+year+"/"+(month)+"/"+day);

int second = cal.get(Calendar.SECOND);
int minute = cal.get(Calendar.MINUTE);
int hour = cal.get(Calendar.HOUR);
Time_txt.setText(" Time  "+hour+":"+minute+":"+second);
          sleep(1000);
      } catch (InterruptedException ex) {
          Logger.getLogger(Librarybookmgmt.class.getName()).log(Level.SEVERE, null, ex);
      }

}

}

};
clock.start();


}
     
     
     
     
     private void Fillcombo(){
try{

String mysql = "select * from borrowedbook";
            pst = con.prepareStatement(mysql);
            rst = pst.executeQuery();
            while(rst.next()){
String name=rst.getString("bookCode");
CmboBookName.addItem(name);
            }            
}catch(Exception e){
JOptionPane.showMessageDialog(null, e);

} finally{
try{
    rst.close();
	pst.close();
	//conn.close();
}catch(Exception e){
		}}}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CmboBookName = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBorrow = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        BtnReturn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtBookAuthour = new javax.swing.JTextField();
        txtBookCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txSearch = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btSave = new javax.swing.JButton();
        BtnClose = new javax.swing.JButton();
        BtnPrint = new javax.swing.JButton();
        btnAddNewUser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblBook = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        date_text = new javax.swing.JMenu();
        Time_txt = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CmboBookName.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                CmboBookNamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel4.setText("Borrowed Book code");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnBorrow.setText("Borrow");
        btnBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowActionPerformed(evt);
            }
        });

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        BtnSave.setText("Add Book");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        BtnReturn.setText("Return");
        BtnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnUpdate)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBorrow)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnReturn)
                    .addComponent(BtnSave))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnBorrow)
                    .addComponent(btnClear))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Book Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 3, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel3.setText("Authour");

        jLabel1.setText("Book Name");

        jLabel2.setText("Book Code");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBookCode, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBookAuthour, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookAuthour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jLabel5.setText("Search By Book Code");

        txSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txSearchKeyReleased(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(0, 0, 255));
        jToolBar1.setRollover(true);

        btSave.setBackground(new java.awt.Color(0, 0, 255));
        btSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSave.setIcon(new javax.swing.ImageIcon("D:\\Tutorial\\Icon Archive\\Floppy-Small-icon.png")); // NOI18N
        btSave.setText("Save");
        btSave.setFocusable(false);
        btSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btSave);

        BtnClose.setBackground(new java.awt.Color(0, 0, 255));
        BtnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraray/Actions-system-shutdown-icon.png"))); // NOI18N
        BtnClose.setText("Close");
        BtnClose.setFocusable(false);
        BtnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnClose);

        BtnPrint.setBackground(new java.awt.Color(0, 0, 255));
        BtnPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnPrint.setIcon(new javax.swing.ImageIcon("D:\\Tutorial\\Icon Archive\\Devices-media-floppy-icon.png")); // NOI18N
        BtnPrint.setText("Print");
        BtnPrint.setFocusable(false);
        BtnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnPrint);

        btnAddNewUser.setBackground(new java.awt.Color(0, 0, 255));
        btnAddNewUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddNewUser.setIcon(new javax.swing.ImageIcon("D:\\Tutorial\\Icon Archive\\Floppy-Small-icon.png")); // NOI18N
        btnAddNewUser.setText("Add New User");
        btnAddNewUser.setFocusable(false);
        btnAddNewUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddNewUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewUserActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAddNewUser);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Available Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        TblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblBookMouseClicked(evt);
            }
        });
        TblBook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TblBookKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TblBook);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jButton1.setText("LogOut");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Close");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        date_text.setText("Date");
        jMenuBar1.add(date_text);

        Time_txt.setText("Time");
        jMenuBar1.add(Time_txt);

        jMenu3.setText("Help");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem3.setText("Help");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(CmboBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CmboBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(223, 223, 223))
        );

        setSize(new java.awt.Dimension(912, 683));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
      try{
            Statement sta=con.createStatement();
            sta.executeUpdate("insert into TblBooks values('"+txtBookName.getText()+"','"+txtBookCode.getText()+"','"+txtBookAuthour.getText()+"')");
            update_table();
            JOptionPane.showMessageDialog(this, "The book is Saved");          
        }catch(HeadlessException | SQLException e){
            System.err.println(e.getMessage());
        }        
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
         txtBookName.setText("");
        txtBookCode.setText("");
        txtBookAuthour.setText("");
       txSearch.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int p=JOptionPane.showConfirmDialog(null, "Do you Realy want to delete ?","Delete",JOptionPane.YES_NO_OPTION);
      if(p==0){
              String sql="delete from TblBooks where bookCode=?";
              String sql2="delete from borrowedbook where bookCode=?";
        try{
         pst=con.prepareStatement(sql);
         pst1=con.prepareStatement(sql2);
         pst.setString(1, txtBookCode.getText());
         pst1.setString(1, txtBookCode.getText());
           pst.execute();
           pst1.execute();
           update_table();
           JOptionPane.showMessageDialog(null, "The Book is deleted");
           
}
catch(Exception e)
{
     JOptionPane.showMessageDialog(null,e);
}
    }             
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
try{
    String val1=txtBookName.getText();
    String val2=txtBookCode.getText();
    String val3=txtBookAuthour.getText();
    
    String sql="update TblBooks set bookName='"+val1+"',bookCode='"+val2+"',bookAuthour='"+val3+"'";
    pst=con.prepareStatement(sql);
    pst.execute();
    update_table();
    JOptionPane.showMessageDialog(null, "Updated");

}
catch(HeadlessException | SQLException e)
{
     JOptionPane.showMessageDialog(null,e);
}
        
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void CmboBookNamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_CmboBookNamePopupMenuWillBecomeInvisible

         String temp=(String)CmboBookName.getSelectedItem();
    String sql= "select * from borrowedbook where bookCode = ? ";
        try{
      pst=con.prepareStatement(sql);
      pst.setString(1, temp);
       rst=pst.executeQuery();
       if(rst.next()){
           String Add1=rst.getString("bookName");
           txtBookName.setText(Add1);
           String Add2=rst.getString("bookCode");
           txtBookCode.setText(Add2);
            String Add3=rst.getString("bookAuthour");
            txtBookAuthour.setText(Add3);
       }
}
catch(Exception e)
{
     JOptionPane.showMessageDialog(null,e);
}
         
    }//GEN-LAST:event_CmboBookNamePopupMenuWillBecomeInvisible

    private void TblBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblBookMouseClicked
        try{
            int row=TblBook.getSelectedRow();
            String Table_click=(TblBook.getModel().getValueAt(row, 1).toString());
            String sql="select *from tblbooks where bookCode='"+Table_click+"' ";
            pst=con.prepareStatement(sql);
            rst=pst.executeQuery();
            if(rst.next()){
           String Add1=rst.getString("bookName");
           txtBookName.setText(Add1);
           String Add2=rst.getString("bookCode");
           txtBookCode.setText(Add2);
            String Add3=rst.getString("bookAuthour");
            txtBookAuthour.setText(Add3);
        }}catch(Exception e){
          JOptionPane.showMessageDialog(null, e);  
        }
    }//GEN-LAST:event_TblBookMouseClicked

    private void txSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSearchKeyReleased
       try{
           String sql="select * from tblbooks where bookCode=?";
           pst=con.prepareStatement(sql);
           pst.setString(1, txSearch.getText());
           rst=pst.executeQuery();
           if(rst.next()){
            String Add1=rst.getString("bookName");
           txtBookName.setText(Add1);
           String Add2=rst.getString("bookCode");
           txtBookCode.setText(Add2);
            String Add3=rst.getString("bookAuthour");
            txtBookAuthour.setText(Add3);
               
           }
           
       }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_txSearchKeyReleased

    private void TblBookKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TblBookKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN || evt.getKeyCode()==KeyEvent.VK_UP){
            try{
            int row=TblBook.getSelectedRow();
            String Table_click=(TblBook.getModel().getValueAt(row, 1).toString());
            String sql="select *from tblbooks where bookCode='"+Table_click+"' ";
            pst=con.prepareStatement(sql);
            rst=pst.executeQuery();
            if(rst.next()){
           String Add1=rst.getString("bookName");
           txtBookName.setText(Add1);
           String Add2=rst.getString("bookCode");
           txtBookCode.setText(Add2);
            String Add3=rst.getString("bookAuthour");
            txtBookAuthour.setText(Add3);
        }}catch(Exception e){
          JOptionPane.showMessageDialog(null, e);  
        }
        }
    }//GEN-LAST:event_TblBookKeyPressed

    private void BtnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturnActionPerformed
        int p=0;
        if(p==0){
             try{
            Statement sta=con.createStatement();
            sta.executeUpdate("insert into TblBooks values('"+txtBookName.getText()+"','"+txtBookCode.getText()+"','"+txtBookAuthour.getText()+"')");
            update_table();
            JOptionPane.showMessageDialog(this, "The book is Returned");
            p=1;
        }catch(HeadlessException | SQLException e){
            System.err.println(e.getMessage());
        }        
        }
        if(p==1){
            
                          String sql="delete from borrowedbook where bookCode=?";
        try{
         pst=con.prepareStatement(sql);
         pst.setString(1, txtBookCode.getText());
           pst.execute();
           update_table();
           //JOptionPane.showMessageDialog(null, "The Book is deleted from borrowed table");
           
}
catch(Exception e)
{
     JOptionPane.showMessageDialog(null,e);
}
        }
    }//GEN-LAST:event_BtnReturnActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       close();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            close();
            Librarybookmgmt nw= new Librarybookmgmt();
            nw.setVisible(true);
        } catch (Exception  ex) {
            JOptionPane.showMessageDialog(null, ex);
            
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowActionPerformed
      int p=0;
        if(p==0){
             try{
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","lelo");
            Statement sta=con.createStatement();
            sta.executeUpdate("insert into borrowedbook values('"+txtBookName.getText()+"','"+txtBookCode.getText()+"','"+txtBookAuthour.getText()+"')");
            update_table();
            JOptionPane.showMessageDialog(this, "The book is borrowed");
            p=1;
            //con.close();
        }catch(HeadlessException | SQLException e){
            System.err.println(e.getMessage());
        }        
        }
        if(p==1){
            
                          String sql="delete from tblbooks where bookCode=?";
        try{
         pst=con.prepareStatement(sql);
         pst.setString(1, txtBookCode.getText());
           pst.execute();
           update_table();
           //JOptionPane.showMessageDialog(null, "The Book is deleted from avialable table");
           
}
catch(Exception e)
{
     JOptionPane.showMessageDialog(null,e);
}
        }
    }//GEN-LAST:event_btnBorrowActionPerformed

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        MessageFormat header = new MessageFormat("report print");
       MessageFormat footer = new MessageFormat("page{0,number,integer}");
try{
TblBook.print(JTable.PrintMode.NORMAL,header,footer);
}catch(java.awt.print.PrinterException e){
System.err.format("cannot print %s%n",e.getMessage());
}
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        close();
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        try{
//         
            Statement sta=con.createStatement();
            sta.executeUpdate("insert into TblBooks values('"+txtBookName.getText()+"','"+txtBookCode.getText()+"','"+txtBookAuthour.getText()+"')");
            update_table();
            JOptionPane.showMessageDialog(this, "The book is Saved");
            //con.close();
        }catch(HeadlessException | SQLException e){
            System.err.println(e.getMessage());
        }        
    }//GEN-LAST:event_btSaveActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
     
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
          try{
Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+ "E:/COVER PAGE.docx");
}
catch(Exception e){
JOptionPane.showMessageDialog(null,"Error");

}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
            close();
        Hompage home=new Hompage();
        home.setVisible(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewUserActionPerformed
        close();
        register reg= new register();
        reg.setVisible(true);
    }//GEN-LAST:event_btnAddNewUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librarybookmgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librarybookmgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librarybookmgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librarybookmgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                try {
                    new Librarybookmgmt().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Librarybookmgmt.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Librarybookmgmt.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClose;
    private javax.swing.JButton BtnPrint;
    private javax.swing.JButton BtnReturn;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JComboBox CmboBookName;
    private javax.swing.JTable TblBook;
    private javax.swing.JMenu Time_txt;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btnAddNewUser;
    private javax.swing.JButton btnBorrow;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JMenu date_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txSearch;
    private javax.swing.JTextField txtBookAuthour;
    private javax.swing.JTextField txtBookCode;
    private javax.swing.JTextField txtBookName;
    // End of variables declaration//GEN-END:variables
}
